### ISSUE TITLE
Question: Using rails for sign-up and sign-in pages

### ISSUE THREAD

**Issue by gbrl** [neroniaky/angular2-token-example#3]
I learned a lot from this example app, thank you for making it!

I have an issue however, related to app file size. It doesn't seem like a good idea to load the entire Angular app on the root "/" of my domain. If users just want to see some info and read the FAQ page, they shouldn't have to download 3MB of JS. So I was wondering about having the homepage, sign-in and sign-up pages not be part of the Angular app. Is this even possible? Can I use regular devise gem views for this? Or will the user only be logged in Rails, and then when Angular loads, the user isn't logged in.

Thanks for your time!

**Comment by neroniaky** [comment]
Hey, I have never tried a combined Rails / Rails API + Angular2 - App, but I gonna try to answer it anyways :).

You could extract websites like FAQ and serve them as static assets outside of Angular2.

The Problem I see for Sign-in/-out is that Devise and Devise Token Auth use different systems of storing the authentication information (not 100% shure here). You would need a system to get the auth information into Angular2.

So what I would suggest is keep the  Sign-in/-out part of Angular and extract the static pages.
