### ISSUE TITLE
SignInOAuth does not work with api-only rails app

### ISSUE THREAD

**Issue by roterski** [neroniaky/angular2-token-example#4]
Rendering rails parts are needed for devise_auth_token OAuth flow to work. It boils down to figuring out which middlewares are needed to be added [here](https://github.com/neroniaky/angular2-token-example/blob/master/config/application.rb#L30).

**Comment by neroniaky** [comment]
Do you think devise_auth_token is still being maintained? Your PR seems to sit there for quite a while already.

**Comment by roterski** [comment]
Yeah, [devise_auth_token](https://github.com/lynndylanhurley/devise_token_auth/pulse/monthly) devs have not been very active lately but I wouldn't yet say it's abandoned - maybe just overwhelmed with PRs and issues.

Anyway, my PR solves that double slash issue but it's not critical at all - turns out redirection works fine even with the double slash. You can see it on [my example app](http://ng2auth-router-starter.netlify.com/).
There I've experienced the same problem angular2-token-example has. It was because of missing rendering middlewares. I was lazy so I fixed that by just making regular rails app, instead of using `api-only` mode. However, I'm convinced that it's possible to tweak `api-only` app to work with it just fine.

**Comment by neroniaky** [comment]
This example has been merged into the main repository. Please refer to https://github.com/neroniaky/angular-token if you have any questions. Thanks!
