### ISSUE TITLE
API access_token use

### ISSUE THREAD

**Issue by tagazok** [neroniaky/angular2-token-example#6]
Hi,

Is it possible to have access to the access_token sent by the provider to then use it to call it's api.
For example, I can log-in with my Instagram. However, if I want to call the Instagram API, I need the access_token sent back by Instagram.

Is this achievable?

**Comment by neroniaky** [comment]
This example has been merged into the main repository. Please refer to https://github.com/neroniaky/angular-token if you have any questions. Thanks!
